"""Add direction description

Revision ID: 0fd42d4992d2
Revises: b7e7c4c8848e
Create Date: 2026-05-27 13:40:18.003200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fd42d4992d2'
down_revision: Union[str, Sequence[str], None] = 'b7e7c4c8848e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('directions', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('directions', 'description')
    # ### end Alembic commands ###
