"""add announcement comments

Revision ID: baab75a93f8e
Revises: 6b51a2173b51
Create Date: 2026-06-19 12:38:25.569988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baab75a93f8e'
down_revision: Union[str, Sequence[str], None] = '6b51a2173b51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcement_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('announcement_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcement_comments_announcement_id'), 'announcement_comments', ['announcement_id'], unique=False)
    op.create_index(op.f('ix_announcement_comments_author_id'), 'announcement_comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_announcement_comments_created_at'), 'announcement_comments', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_announcement_comments_created_at'), table_name='announcement_comments')
    op.drop_index(op.f('ix_announcement_comments_author_id'), table_name='announcement_comments')
    op.drop_index(op.f('ix_announcement_comments_announcement_id'), table_name='announcement_comments')
    op.drop_table('announcement_comments')
    # ### end Alembic commands ###
