"""add slot description

Revision ID: f138a46b20b0
Revises: 5de1f51bbe6c
Create Date: 2026-06-11 23:02:19.238815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f138a46b20b0'
down_revision: Union[str, Sequence[str], None] = '5de1f51bbe6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slots', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slots', 'description')
    # ### end Alembic commands ###
